services:
  postgres:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres=${POSTGRES_DB}
    ports:
      - 5432:5432
  
  mysql:
    image: mysql:8.2.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}
    ports:
    - 3306:3306